<a href="https://colab.research.google.com/github/MauriceLaf/CAP4630/blob/master/Homework_1_MauriceLaflamme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 1

###Imports and Exceptions

In [0]:
import numpy as np

In [0]:
class MatrixNotCompatibleException(Exception):
    """Raised when incompatible matrices are multiplied"""
class EmptyList(Exception):
    """Raised when list is empty"""

Multiply Matrices Function
-----
#####This function takes in a list of numpy arrays and multiplies them together, if they are compatible.





A matrix, M, can be multiplied with another matrix, N, when the matrix M has as many columns as the matrix N has rows. An example of two compatible matrices would be as follows:

$$M=
  \begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    1 & 2 & 3 & 4 & 5
  \end{bmatrix}$$

$$N=
  \begin{bmatrix}
    1 & 2 \\
    2 & 3 \\
    3 & 4 \\
    4 & 5 \\
    5 & 6
  \end{bmatrix}$$


In [0]:
def multiply_matrices(matrices):
    if not matrices:
        print("ERROR: List is empty")
        raise EmptyList
    flag = 1
    for matrix in matrices:
        if flag == 1:
            flag = 0
            prevMatrix = matrix
        else:
            if prevMatrix.shape[1] != matrix.shape[0]:
                print("ERROR: Cannot multiply first/previously determined product:")
                print(prevMatrix)
                print("with:")
                print(matrix)
                print("There is a column/row mismatch.")
                raise MatrixNotCompatible
            else:
                prevMatrix = prevMatrix.dot(matrix)
    print("Final Answer is:")
    print()
    print(prevMatrix)


Test Cases
-----




###Case 1


This first test case involves multiplying three matrices: L, M, and N.

$$L=
  \begin{bmatrix}
    0 & 1 & 1 \\
    4 & 5 & 1 \\
    2 & 3 & 4
  \end{bmatrix}$$

$$M=
  \begin{bmatrix}
    1 & 2 \\
    2 & 3 \\
    1 & 2 \\
  \end{bmatrix}$$
$$N=
  \begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    1 & 2 & 3 & 4 & 5 \\
    1 & 2 & 3 & 4 & 5
  \end{bmatrix}$$


These are not compatible, as the output of L * M is

$$L * M=\begin{bmatrix}
    3 & 5 \\
    15 & 25 \\
    12 & 21 \\
  \end{bmatrix}
$$ 

Which contains 2 columns, while N has 3 rows. This will lead to an exception due to the mismatch.

In [119]:
array1 = np.array(([[0,1,1],
                    [4,5,1],
                    [2,3,4]]))
array2 = np.array([[1,2],
                   [2,3],
                   [1,2]])
array3 = np.array([[1,2,3,4,5],
                   [1,2,3,4,5],
                   [1,2,3,4,5]])
test = [array1, array2, array3]
print(test[0])
print(test[1])
print(test[2])
print()
print()
multiply_matrices(test)

[[0 1 1]
 [4 5 1]
 [2 3 4]]
[[1 2]
 [2 3]
 [1 2]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


ERROR: Cannot multiply first/previously determined product:
[[ 3  5]
 [15 25]
 [12 21]]
with:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
There is a column/row mismatch.


MatrixNotCompatible: ignored

###Case 2

This next test case involves multiplying three matrices: L, M, and N.

$$L=
  \begin{bmatrix}
    0 & 1 & 1 \\
    4 & 5 & 1 \\
    2 & 3 & 4
  \end{bmatrix}$$

$$M=
  \begin{bmatrix}
    1 & 2 \\
    2 & 3 \\
    1 & 2 \\
  \end{bmatrix}$$
$$N=
  \begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    1 & 2 & 3 & 4 & 5 
  \end{bmatrix}$$

These are extremely similar to the first test cases matrices, but N is now only 2 rows. This removes the column/row mismatch.

In [120]:
array1a = np.array(([[0,1,1],
                     [4,5,1],
                     [2,3,4]]))
array2a = np.array([[1,2],
                    [2,3],
                    [1,2]])
array3a = np.array([[1,2,3,4,5],
                    [1,2,3,4,5]])
test1 = [array1a, array2a, array3a]
print(test1[0])
print(test1[1])
print(test1[2])
print()
print()
multiply_matrices(test1)

[[0 1 1]
 [4 5 1]
 [2 3 4]]
[[1 2]
 [2 3]
 [1 2]]
[[1 2 3 4 5]
 [1 2 3 4 5]]


Final Answer is:

[[  8  16  24  32  40]
 [ 40  80 120 160 200]
 [ 33  66  99 132 165]]


###Case 3

Empty List Case

In [122]:
nolist = []
multiply_matrices(nolist)

ERROR: List is empty


EmptyList: ignored