<a href="https://colab.research.google.com/github/MauriceLaf/CAP4630/blob/master/HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Number 1

###Define Function (s)
I defined an extra function since I initially misunderstood the test cases

SOURCE: https://stackoverflow.com/questions/54962004/implement-max-mean-poolingwith-stride-with-numpy

In [0]:
import numpy as np

class CustomError(Exception):
  pass

##Essentially the same as conv2d but I made it to read from a list of arrays before I looked at the test cases
def conv2dList(input_mat, kernel_mat):
  mList = []
  for i in range(len(input_mat)):
    inp = input_mat[i]
    kern = kernel_mat[i]

    filter_shape = tuple(np.subtract(inp.shape, kern.shape) + 1)
    strides = inp.strides + inp.strides
    
    if (filter_shape[0] < 0 or filter_shape[1] < 0):
      print("[]")
      mList.append([])
      continue

    sub_matrices = np.lib.stride_tricks.as_strided(inp, kern.shape + filter_shape, strides)

    m = np.einsum('ij,ijkl->kl', kern ,sub_matrices)
    mList.append(m)
    print(m)
  return mList


def conv2d(input_mat, kernel_mat):
  inp = input_mat
  kern = kernel_mat

  if input_mat.shape[0] != input_mat.shape[1] or kernel_mat.shape[0] != kernel_mat.shape[1]:
    raise CustomError("Both Matrices Must Be Square Matrices")

  filter_shape = tuple(np.subtract(inp.shape, kern.shape) + 1)
  strides = inp.strides + inp.strides
    
  if (filter_shape[0] < 0 or filter_shape[1] < 0):
    print("[]")
    return []

  sub_matrices = np.lib.stride_tricks.as_strided(inp, kern.shape + filter_shape, strides)

  m = np.einsum('ij,ijkl->kl', kern ,sub_matrices)
  print(m)
  return m


###Create Test Case Arrays


In [0]:
input_mat = []
kernel_mat = []
expected_mat = []

##Test Case 1##
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 1, 2, 1],
                           [1, 2, 1, 2],
                           [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                              [4, 2, 4],
                              [2, 4, 2]]))

##Test Case 2##
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0], 
                            [0, 1]]))

expected_mat.append(np.array([[2, 0, 0], 
                              [0, 2, 0], 
                              [0, 0, 2]]))


##Test Case 3##
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, -1],
                            [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], 
                              [-1,  1, -1],
                              [ 0, -1,  1]]))

##Test Case 4##
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))

##Test Case 5##
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append([])

### #1 Test Cases

In [4]:
for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
[[4]]
Correct output!

[]
[]
Correct output!



##Number 2

###Define Function

SOURCE: https://stackoverflow.com/questions/54962004/implement-max-mean-poolingwith-stride-with-numpy

In [0]:
def maxpooling2d(input_mat, s):
  mat = input_mat
  
  if (mat.shape[0] != mat.shape[1]):
    raise CustomError("Matrix Must Be A Square Matrix")
  ##Round Up From Division
  shape0 = (mat.shape[0] - s)//2 + 1
  shape1 = (mat.shape[1] - s)//2 + 1

  output_shape = (shape0, shape1)

  s_size = (s, s)
  shape = output_shape + s_size
  strides = (2*mat.strides[0], 2*mat.strides[1]) + mat.strides
  res_mat = np.lib.stride_tricks.as_strided(mat, shape = shape, strides = strides)
  res_mat = res_mat.reshape(-1, *s_size)
  print(res_mat.max(axis=(1,2)).reshape(output_shape))
  return res_mat.max(axis=(1,2)).reshape(output_shape)

###Define Test Cases

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


###Run Test Cases

In [19]:
for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4 2]
 [2 4]]
[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
